handle rust panic errors when getting config for obstore (#8658)
## 📝 Summary

<!--
Provide a concise summary of what this pull request is addressing.

If this PR closes any issues, list them here by number (e.g., Closes
#123).
-->
Sometimes obstore raises a rust panic which bypasses Exception catch
during get_config. Thus, check for BaseException instead.

I thought about adding a BaseException catch in the parent
(`hooks_post_execution.py`) but this might swallow genuine errors we
want to raise like KeyboardInterrupt.

```
[D 260312 14:39:09 hooks_post_execution:248] Broadcasting storage namespaces

thread '<unnamed>' (28138113) panicked at pyo3-object_store/src/aws/store.rs:254:14:
Expected config prefix to start with aws_
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[E 260312 14:39:09 storage:154] Failed to get endpoint from store config
    Traceback (most recent call last):
      File "/Users/slourdusamy/Development/marimo/marimo/_data/_external_storage/storage.py", line 151, in _get_config
        return store.config
               ^^^^^^^^^^^^
    pyo3_runtime.PanicException: Expected config prefix to start with aws_
```

## 🔍 Description of Changes

<!--
Detail the specific changes made in this pull request. Explain the
problem addressed and how it was resolved. If applicable, provide before
and after comparisons, screenshots, or any relevant details to help
reviewers understand the changes easily.
-->

## 📋 Checklist

- [x] I have read the [contributor
guidelines](https://github.com/marimo-team/marimo/blob/main/CONTRIBUTING.md).
- [ ] For large changes, or changes that affect the public API: this
change was discussed or approved through an issue, on
[Discord](https://marimo.io/discord?ref=pr), or the community
[discussions](https://github.com/marimo-team/marimo/discussions) (Please
provide a link if applicable).
- [x] Tests have been added for the changes made.
- [ ] Documentation has been updated where applicable, including
docstrings for API changes.
- [x] Pull request title is a good summary of the changes - it will be
used in the [release
notes](https://github.com/marimo-team/marimo/releases).