fix: do not mutate the test environment during tests (#9305)
This PR fixes a test regression caused by tests that mutated the test
virtual environment.

A few code mode tests were calling `uv add` and `uv remove`. This synced
the environment to marimo's dependencies and deleted all the test
dependencies. This led to many errors that looked different
(multiprocessing.spawn failing to start, various packages failing to
import) but that were all symptoms of the same issue .

In this change, we mock the package manager. We also add a test fixture
that detects venv environment corruption and fails fast to prevent this
from happening again.

Before this change, 45+ tests were failing. With the following four
tests are failing on Ubuntu, macOS, and Windows. These tests are
unrelated to the root cause addressed in this PR.

```
FAILED tests/_plugins/ui/_impl/test_table.py::test_download_as[df0] - AssertionError
FAILED tests/_plugins/ui/_impl/test_table.py::test_get_data_url_no_deps - AssertionError: assert False
 +  where False = <built-in method startswith of str object at 0x7f8e887c9390>('data:application/json;base64,')
 +    where <built-in method startswith of str object at 0x7f8e887c9390> = 'data:text/csv;base64,dmFsdWUKMQoyCjMK'.startswith
 +      where 'data:text/csv;base64,dmFsdWUKMQoyCjMK' = GetDataUrlResponse(data_url='data:text/csv;base64,dmFsdWUKMQoyCjMK', format='csv').data_url
FAILED tests/_server/api/endpoints/test_assets.py::test_serve_static_allowed_files - RuntimeError: File at path /home/runner/work/marimo/marimo/marimo/_static/manifest.json does not exist.
FAILED tests/_runtime/test_complete.py::test_get_completion_options_bails_out_when_timeout_elapsed - AssertionError: assert 'function' == ''
```