feat: CLI update secure docker to python3.14
Also /app does not exist, so use /home for work directory.

Fixes:

$ marimo edit --sandbox https://molab.marimo.io/notebooks/nb_g6ygAQ8b1HMSaoszTGEGqy
This notebook is hosted on a remote server.
Would you like to run it in a secure docker container? [Y/n]: y
Starting containerized marimo notebook
Running command: docker run --rm -d -p 8080:8080 -e MARIMO_MANAGE_SCRIPT_METADATA=true -e MARIMO_IN_SECURE_ENVIRONMENT=true -w /app ghcr.io/astral-sh/uv:0.4.21-python3.12-bookworm uvx marimo edit --sandbox --no-token -p 8080 --host 0.0.0.0 https://molab.marimo.io/notebooks/nb_g6ygAQ8b1HMSaoszTGEGqy
Failed to start Docker container: Command '['docker', 'run', '--rm', '-d', '-p', '8080:8080', '-e', 'MARIMO_MANAGE_SCRIPT_METADATA=true', '-e', 'MARIMO_IN_SECURE_ENVIRONMENT=true', '-w', '/app', 'ghcr.io/astral-sh/uv:0.4.21-python3.12-bookworm', 'uvx', 'marimo', 'edit', '--sandbox', '--no-token', '-p', '8080', '--host', '0.0.0.0', 'https://molab.marimo.io/notebooks/nb_g6ygAQ8b1HMSaoszTGEGqy']' returned non-zero exit status 126.
Stopping and removing container...
Container stopped and removed successfully

Error: workdir "/app" does not exist on container def1e28dd32293cfd511fa4f3a67cae27a4f101aaca95d9c3a0e7c97a27186b7

and

error: No interpreter found for Python >=3.14 in virtual environments, managed installations, or system path