enhancement: raise a UsageError on marimo edit --sandbox (#5511)
Today, we (silently) don't support multi-notebook edit servers in
sandbox mode. Running

```
marimo edit --sandbox # or marimo edit --sandbox directory/
```
yields confusing behavior in which notebooks all share the same
environment, even though their inline script metadata is kept separate.
This isn't what the users want, and can lead to dependencies missing in
notebook metadata.

Instead of failing silently, this change raises a UsageError if the user
attempts to run the edit server in sandbox mode without a named notebook
argument. It also links to the associated GitHub issue (#2598) .

Here is the usage error:

```
Error: marimo's package sandbox requires a notebook name:

    * marimo edit --sandbox my_notebook.py

  Multi-notebook sandboxed servers (marimo edit --sandbox) are not supported.
  Follow this issue at: https://github.com/marimo-team/marimo/issues/2598.
```

**Bypass with `--dangerous-sandbox`**. For users who really want to use
sandbox mode despite the issues described here and in
https://github.com/marimo-team/marimo/issues/5219, this PR adds a hidden
`--dangerous-sandbox` argument that bypasses the `UsageError`.

Closes #5219.

**API**: This is a breaking change to our CLI. Hopefully people aren't
using `marimo edit --sandbox` in critical scenarios, since it doesn't
really work.

The VSCode extension will need to be updated to use
`--dangerous-sandbox` instead of `--sandbox`.