fix: safer windows logging on PermissionErrors (#6735)
Fixes #6669

This provides a fallback for windows logging which can throw errors like
the below

```
--- Logging error ---
Traceback (most recent call last):
    self.rotate(self.baseFilename, dfn)
  File "C:\Users\nplev\AppData\Roaming\uv\python\cpython-3.11.13-windows-x86_64-none\Lib\logging\handlers.py", line 115, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\nplev\\.cache\\marimo\\logs\\marimo.log' -> 'C:\\Users\\nplev\\.cache\\marimo\\logs\\marimo.log.2025-10-04'
```