fix: `typos` failing on pre-commit CI (#4874)
## 📝 Summary

Fixes pre-commit failures following recommendation to set
`pass_filenames: false` from
https://github.com/crate-ci/typos/issues/926

## 🔍 Description of Changes

- [x] add the `pass_filenames: false` workaround
- [ ] fix typos in codebase which were smuggled through while the
`typos` check was malfunctioning; :confused: while it passes on CI, it
fails locally for me on:
   ```

typos....................................................................Failed
    - hook id: typos
    - exit code: 2
    
    error: `fo` should be `of`, `for`, `do`, `go`, `to`
      --> ./codemirror-languageserver-marimo/src/utils.test.ts:117:35
        |
117 | expect(createMockContext("fo").matchBefore(pattern)).toEqual({
        |                                   ^^
        |
    error: `fo` should be `of`, `for`, `do`, `go`, `to`
      --> ./codemirror-languageserver-marimo/src/utils.test.ts:120:20
        |
    120 |             text: "fo",
        |                    ^^
        |
    ```

## 📋 Checklist

- [x] I have read the [contributor
guidelines](https://github.com/marimo-team/marimo/blob/main/CONTRIBUTING.md).
- [x] I have run the code and verified that it works as expected.

## 📜 Reviewers

@mscolnick